CREATE TABLE USER
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  LOGIN VARCHAR(30) NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  SURNAME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(60) NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL
);
CREATE TABLE BANK_ACCOUNT
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ACCOUNT_NUMBER INTEGER NOT NULL,
  ACCOUNT_VALUE DOUBLE,
  USER_ID INTEGER,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON UPDATE CASCADE
);
CREATE TABLE HISTORY
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  DATE VARCHAR(40) NOT NULL,
  OPERATION VARCHAR(30),
  USER_ID INTEGER,
  BANK_ACCOUNT_ID INTEGER,
  REASON VARCHAR(100) NOT NULL,
  MONEY DOUBLE NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON UPDATE CASCADE,
  FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT (ID) ON UPDATE CASCADE
);
CREATE TABLE ROLE
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ROLE_NAME VARCHAR(15),
  USER_ID INTEGER,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE SET NULL ON UPDATE CASCADE
);

INSERT INTO USER (ID, LOGIN, NAME, SURNAME, EMAIL, PASSWORD) VALUES (1, 'root', 'root', 'root', 'root','root');
INSERT INTO ROLE (ROLE_NAME, USER_ID) VALUES ('ROLE_ADMIN',1);
INSERT  INTO  BANK_ACCOUNT (ID, ACCOUNT_NUMBER, ACCOUNT_VALUE, USER_ID) VALUES (1,1,1000,1);